### ISSUE TITLE
[Feature] Add ability to retag existing docker image

### ISSUE THREAD

**Issue by zahradtj** [drone-plugins/drone-docker#133]
My team uses the tag "latest" for test/non-prod builds, then we retag the image with a version number once it has gone through various automated and manual tests.  When we were using Jenkins we were able to pull down the existing :latest image and retag it as :version-number using `docker tag application:latest application:1.0` .  We would like to replicate this functionality in drone, however in our environment we are unable to run privileged docker images inside drone.

Is it possible to add retag functionality to this plugin?

**Comment by donny-dont** [comment]
All the official plugins are meant to be simple. You can fork the plugin or roll your own if your environment has very specific requirements.

**Comment by bradrydzewski** [comment]
@donny-dont is correct. This plugin has very limited scope and is not intended to satisfy all possible use cases. You can create your own plugin or fork and alter this plugin to meet your specific needs.

In addition, you can mount the host machine docker socket and interact directly with the docker daemon for additional flexibility. For an example see http://docs.drone.io/docker-volumes/

**Comment by thomasf** [comment]
A way to get this is to create a new plugin which uses crane ( https://github.com/google/go-containerregistry/blob/master/cmd/crane/doc/crane_copy.md ) to copy images inside a registry without even downloading it because it only replicates image metadata.

It defaults to using the normal docker client auth from ~/.docker/config.json

It is invoked via command line like this so it should be easy to wrap inside a plugin:

```sh
crane copy registry.example.com/myapp/app:master   registry.example.com/myapp/app:1.0
```
