### ISSUE TITLE
Multi-architecture using Docker manifest

### ISSUE THREAD

**Issue by lflare** [drone-plugins/drone-docker#158]
Like currently implemented in the official images, I believe `plugins/docker` can be multi-arched using the Docker manifest tools?

EDIT: This might be of [good reference](https://developer.ibm.com/linuxonpower/2017/07/27/create-multi-architecture-docker-image/)...

**Comment by tboerger** [comment]
We still need to push the different tags, but with the manifest tool we can map to them from the main image

**Comment by Lerentis** [comment]
coming back to the multiarch topic two years later, could this plugin support building using [buildx](https://github.com/docker/buildx)?

**Comment by tboerger** [comment]
Nothing has changed and it won't change. Use the docker plugin per architecture, after that write the manifest with the manifest plugin.

**Comment by tboerger** [comment]
And the docker plugin itself is built with a manifest.

**Comment by bradrydzewski** [comment]
> coming back to the multiarch topic two years later, could this plugin support building using buildx?

buildx is still experimental so we need to wait and see if and when it gets integrated into the stable channel. If buildx is supported mainline it is possible we could support in this plugin. This plugin is built on top of the official docker image, so we would need the official docker image to support buildx and ship with qemu properly configured. We also need to evaluate the effectiveness of buildx and qemu emulation on cloud vms, since performance may be questionable.
