### ISSUE TITLE
Error spam

### ISSUE THREAD

**Issue by let4be** [drone-plugins/drone-docker#38]
```
time="2016-02-12T19:47:21.836933519Z" level=error msg="Couldn't run auplink before unmount: exec: \"auplink\": executable file not found in $PATH" 
time="2016-02-12T19:47:21.880847240Z" level=error msg="Couldn't run auplink before unmount: exec: \"auplink\": executable file not found in $PATH
```

during the deploy

**Comment by bradrydzewski** [comment]
This is output by docker itself and not something we have control over, nor does it impact the ability to publish a container. It is based on your host environment, and could be triggered by different OS configuration.

If you look at the drone project, for example, we don't get this error:
http://beta.drone.io/drone/drone/264

We can re-open this issue if we determine there is something we can do from within drone, but since this comes from Docker I'm not sure there is anything we can do.

**Comment by let4be** [comment]
I think this could be fixed by installing auf-utils package? am I wrong?

**Comment by let4be** [comment]
@bradrydzewski this one: https://packages.debian.org/ru/wheezy/aufs-tools
>> It is based on your host environment, and could be triggered by different OS configurations.
how so? drone runs in its own docker container with it's own environment

**Comment by let4be** [comment]
@bradrydzewski also see http://high.io/2014/05/26/docker-installation-on-bare-ubuntu-14.04-lts/
