### ISSUE TITLE
docker push to registry fails without email address

### ISSUE THREAD

**Issue by curtismitchell** [drone-plugins/drone-docker#63]
I was unable to push to a private registry that is secured by htpasswd (username and password).  My `.drone.yml` file had the username and password values, but I omitted the email value.  I was able to get the push to work by adding a bogus email address to the `.drone.yml` file.  This seems like a bug. Or, I am misunderstanding something.  Please help me understand.

**Comment by bradrydzewski** [comment]
prior to Docker 1.11 email was required, and the 0.4 version of this plugin is based on 1.11

the 0.5 version of this plugin makes email optional. 0.5 is not yet released, however, this is already fixed in the master branch in preparation.

my recommendation is to use the dummy email until 0.5 is launched.
