### ISSUE TITLE
Make --pull=true optional in build command

### ISSUE THREAD

**Issue by inoc603** [drone-plugins/drone-docker#93]
Currently the `--pull=true` is a fixed value in the build command. I think it would be better to make it an option in the config, to avoid pulling the base image every time.

**Comment by tboerger** [comment]
I don't know any case where you want to build on an outdated image.

**Comment by inoc603** [comment]
The base image usually does not change very often, and if it uses a exact tag rather than `latest`, there's need to pull this kind of image every time.

**Comment by bradrydzewski** [comment]
--pull only pulls if the local cache does not have the latest sha for the requested tag. If a local copy is up to date, at worst, it will add an extra http request.

**Comment by inoc603** [comment]
@bradrydzewski yes, I understand how tags and layers work. I open this issue because I've experienced some quite slow builds with drone, and the attempts to pull the latest base image are the most time consuming step. They sometimes hang up completely due to my poor network speed, even when the base image is the tiny `busybox`, which is up-to-date on the host machine.

Maybe we can make `pull` configurable for special cases like mine, while having `pull=true` as default, and all pipelines can work as they used to.

**Comment by inoc603** [comment]
This shouldn't be so hard, and I'll try make a PR which does not affect existing workflows.

**Comment by tboerger** [comment]
This won't change anything since this plugin uses docker in docker, you need to use a cache plugin to speed it up

**Comment by bradrydzewski** [comment]
@tboerger is correct. The drone build environment is ephemeral which means when the build is done, the entire environment (including /var/lib/docker) is destroyed. So --pull is not impacting the performance.

If you want to improve performance you need to cache the docker directory. This can be done using a caching plugin. See the following example in the docs:
https://github.com/drone-plugins/drone-docker/blob/master/DOCS.md#caching

Closing since I think caching is the answer here, and not `--pull=false`

**Comment by inoc603** [comment]
Oh, I thought the plugin mount the host docker, my bad.

Thanks a lot, I'll look into the caching stuff instead. Appreciate your fast response and detailed explanation, you guys are amazing.
